/**
 * Startup banner: shows the payo logo plus a short orientation note, once when
 * the CLI launches before the questionnaire begins.
 *
 * The logo is rendered as a real inline image when the terminal supports a
 * graphics protocol (iTerm2 / WezTerm / VS Code / Kitty / Ghostty), and falls
 * back to pre-rendered terminal art (chafa block symbols) everywhere else.
 * Dependency-free.
 *
 * Both logos are baked into logo.data.ts rather than read from assets/ at
 * runtime, so a `bun build --compile` binary carries them with it.
 */
import { note } from '@clack/prompts';
import pkg from '../../package.json';
import { LOGO_ANS, LOGO_PNG_BASE64, LOGO_PNG_BYTES } from './logo.data';

const useColor = process.stdout.isTTY && process.env.NO_COLOR === undefined;

/** Width the inline logo occupies, in terminal cells. */
const LOGO_COLS = 16;

/** Which inline-image protocol the current terminal speaks, if any. */
type ImageProtocol = 'iterm' | 'kitty' | null;

function detectImageProtocol(): ImageProtocol {
  const term = process.env.TERM ?? '';
  const prog = process.env.TERM_PROGRAM ?? '';

  // Kitty graphics protocol: kitty itself and Ghostty.
  if (term === 'xterm-kitty' || process.env.KITTY_WINDOW_ID || prog === 'ghostty') {
    return 'kitty';
  }
  // iTerm2 inline-image protocol: iTerm2, WezTerm, VS Code, Konsole, Tabby.
  if (
    prog === 'iTerm.app' ||
    prog === 'WezTerm' ||
    prog === 'vscode' ||
    prog === 'Tabby' ||
    process.env.LC_TERMINAL === 'iTerm2' ||
    process.env.KONSOLE_VERSION
  ) {
    return 'iterm';
  }
  return null;
}

/** Encode the logo for iTerm2's OSC 1337 inline-image protocol. */
function itermImage(b64: string): string {
  const args = `inline=1;width=${LOGO_COLS};preserveAspectRatio=1;size=${LOGO_PNG_BYTES}`;
  return `\x1b]1337;File=${args}:${b64}\x07`;
}

/**
 * Encode the logo for the Kitty graphics protocol. The payload is transmitted
 * and displayed (a=T) as a PNG (f=100), scaled to LOGO_COLS columns, in 4096-byte
 * base64 chunks. Trailing newlines move the cursor below the image.
 */
function kittyImage(b64: string): string {
  const chunkSize = 4096;
  const chunks: string[] = [];
  for (let i = 0; i < b64.length; i += chunkSize) {
    chunks.push(b64.slice(i, i + chunkSize));
  }
  // Rows to reserve below: cols * aspect / cell-aspect(~2). Conservative guess.
  const rows = Math.max(1, Math.round(LOGO_COLS * 1.4 * 0.5));
  let out = '';
  chunks.forEach((chunk, i) => {
    const more = i < chunks.length - 1 ? 1 : 0;
    // C=1 pins the cursor (some terminals, e.g. Ghostty, otherwise advance it
    // below the image — then the trailing newlines below would double the gap).
    const control = i === 0 ? `a=T,f=100,c=${LOGO_COLS},r=${rows},C=1,m=${more}` : `m=${more}`;
    out += `\x1b_G${control};${chunk}\x1b\\`;
  });
  return out + '\n'.repeat(rows);
}

/** Render the logo as a real inline image, or null if unsupported. */
function imageLogo(): string | null {
  const proto = detectImageProtocol();
  if (!proto) return null;
  return proto === 'kitty' ? kittyImage(LOGO_PNG_BASE64) : itermImage(LOGO_PNG_BASE64);
}

/**
 * Pre-rendered terminal art of the logo (truecolor block symbols, generated
 * from logo.png via chafa).
 */
function asciiLogo(): string {
  // Collapse the asset's trailing blank line(s) so the logo sits flush
  // against the welcome note (console.log adds the one separating newline).
  return LOGO_ANS.replace(/\s*$/, '');
}

/** One-line summary plus the controls the user can rely on during a run. */
const DESCRIPTION = [
  `payo v${pkg.version}`,
  '',
  'payo generates Agent Skills tailored to your stack — one universal layout',
  '(AGENTS.md + .agents/skills) that works across Claude Code, Codex, Cursor,',
  'Copilot, Gemini, Antigravity, Windsurf & Zed. Write once, use in every agent.',
  '',
  'It detects your stack across 8 languages, then asks a few questions and',
  'writes skills your AI agents follow from the very first prompt.',
  '',
  'Payo drives your own installed AI CLI (already signed in) locally to write',
  'those files — nothing is generated by a payo-hosted service.',
  '',
  'Controls:',
  '  • Press Ctrl+C any time to stop — your answers are saved.',
  '  • Re-run payo to resume exactly where you left off.',
].join('\n');

/** Print the logo and orientation note. Call once at CLI startup. */
export function printBanner(): void {
  if (useColor) {
    const art = imageLogo() ?? asciiLogo();
    // eslint-disable-next-line no-console
    if (art) console.log(art);
  }
  note(DESCRIPTION, 'Welcome to payo');
}
